#spring:
#  application:
#    name: jobpilot-backend
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/jobpilot?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata
#    username: root
#    password: root
#
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#
#rapidapi:
#  key: d580a64eaamsh69b074872aff271p1c996djsnd98766b54526
#  host: jsearch.p.rapidapi.com
#
#jwt:
#  secret: your-super-long-secret-key-minimum-32-characters
#  expiration: 900000
#
#server:
#  port: 8080
#
#logging:
#  level:
#    org.springframework.security: INFO
#    org.flywaydb: INFO
#
#file:
#  upload-dir: uploads/resumes

spring:
  application:
    name: jobpilot-backend

  datasource:
    url: jdbc:mysql://localhost:3306/jobpilot?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

rapidapi:
  key: d580a64eaamsh69b074872aff271p1c996djsnd98766b54526
  host: jsearch.p.rapidapi.com

jwt:
  secret: your-super-long-secret-key-minimum-32-characters
  expiration: 900000

server:
  port: 8080

logging:
  level:
    org.springframework.security: INFO
    org.flywaydb: INFO

file:
  upload-dir: uploads/resumes