ALTER TABLE jobs
ADD COLUMN source VARCHAR(100);

ALTER TABLE jobs
ADD COLUMN external_job_id VARCHAR(255);

ALTER TABLE jobs
ADD COLUMN posted_date TIMESTAMP NULL;

ALTER TABLE jobs
ADD COLUMN last_seen TIMESTAMP NULL;